ダイスBot作成
t0rn4t0/discord_bot pull request #10
Opened 2022-05-24 13:10 UTC by ny25mk

ダイスBot作りました。

1D10
2D6+6
1D100 50
1D100 30+30

みたいにチャットすると返してくれます。

2022-05-25 10:25 UTC, t0rn4t0 commented
機能は問題ない気がする！（まだ全部見れてないけど。
以下の対応をお願いします！

- [ ] TRPG_BOTフォルダを作って、そこに格納
- [ ] 使い方的なReadMeをAsciiDocで書く
- [ ] コメントをもっと振ってほしい...（切実）

コメントの例）

>     #ちょっと考えどころ　-> TODO：リファクタ
>     if message.channel.id not in reaction_channel_ids:
>         return

> if __name__ == '__main__':　　＜　これなにやってるかわからんかった；；
>     token_key = read_token_key()
>     client.run(token_key)

2022-05-25 10:30 UTC, t0rn4t0 commented on trpg_bot.py
> +if __name__ == '__main__':
__name__とは...

2022-05-25 11:20 UTC, t0rn4t0 requested changes
とりあえず上の対応をお願いします(*- -)(*_ _)ペコリ
ソースもレビューしましたーので、確認お願いします。

2022-05-25 11:20 UTC, t0rn4t0 commented on dice_goddess.py
> +    pattern = r'([0-9]+)[dD]([0-9]+)[\+\-]?([0-9]+)?\s?([0-9]+)?[\+\-]?([0-9]+)?'
この辺の仕様を話したかった。。。
とりあえず現状の仕様で仕様書を書いてほしいー

2022-05-25 11:41 UTC, ny25mk commented on trpg_bot.py
> +    #ちょっと考えどころ
TODOかToDoかどっちがいい？
どっちでもいいならToDo表記にする

2022-05-25 11:42 UTC, ny25mk commented on trpg_bot.py
> +async def on_ready():
了解

2022-05-25 11:42 UTC, t0rn4t0 commented on trpg_bot.py
> +    #ちょっと考えどころ
Todoでおっけーよ！

2022-05-25 11:43 UTC, ny25mk commented on trpg_bot.py
> +if __name__ == '__main__':
実行されたのが自身だったらってやつだね
単体でテストしたいときはこのif文上で何かやるのがいいかな

2022-05-25 11:44 UTC, ny25mk commented on trpg_bot.py
> +import re
reは正規表現使うためのやつだね

2022-05-25 11:44 UTC, t0rn4t0 commented on trpg_bot.py
> +async def on_ready():
質問とかじゃなければリアクションぐらいで大丈夫よ。
普通に反映してくれれば👌

2022-05-25 11:46 UTC, t0rn4t0 commented on trpg_bot.py
> +async def on_ready():
なんならリアクションもなくてもいい笑
指摘事項のだけだからいちいちひとつづつ返してたら面倒いでしょ。
治ってなかったらまた言うし。

俺が質問したところやゆうたからなんかある時に返信くだされ🙇

2022-05-25 11:51 UTC, ny25mk commented on trpg_bot.py
> +from dice_goddess import *
今モジュール1つしか使ってないからその表記でもいいとは思うんだけど、数増えてきたらめんどくさいんだよね・・・
ここは考えさせてほしい。

2022-05-25 11:55 UTC, t0rn4t0 commented on dice_goddess.py
> +    pattern = r'([0-9]+)[dD]([0-9]+)[\+\-]?([0-9]+)?\s?([0-9]+)?[\+\-]?([0-9]+)?'
納期とかないのでがんがん時間使っちゃってくだされ。
現状の機能の列挙ぐらいで大丈夫だから
フォーマットとかも全く気にしなくていい

2022-05-26 13:40 UTC, ny25mk commented
レビューの対応と使い方説明、プログラム仕様書を追加しました。

2022-05-27 12:49 UTC, t0rn4t0 requested changes
レビューしましたー！
あとadocでもお願いします(*- -)(*_ _)ペコリ

2022-05-27 12:49 UTC, t0rn4t0 commented on TrpgBot/プログラム仕様書.md
> +### 改訂履歴
更新履歴はGitで管理できるので大丈夫ですー

2022-05-27 12:49 UTC, t0rn4t0 commented on TrpgBot/プログラム仕様書.md
> +- Python3.9.7
Python 3.9.7
くそ細かいけど...

2022-05-27 12:49 UTC, t0rn4t0 commented on TrpgBot/trpg_bot.py
> +#もし気になるようなら下のような書き方にしてみる(意味合いは変わらないが、どこのモジュールかは追える)
下のほうがいいかなー。VScode ならアスタリスクでも追えるんだけどね。

2022-05-27 12:49 UTC, t0rn4t0 commented on TrpgBot/trpg_bot.py
> +    977435965561896973
977435965561896973　//　集い->研究室->実験場
って感じでどのチャンネルかわかるようにしといてほしい

2022-05-27 12:49 UTC, t0rn4t0 commented on TrpgBot/trpg_bot.py
> +client = discord.Client(intents=intents)
これってしたの書き方じゃだめなん？
> intents=intents

2022-05-27 12:49 UTC, t0rn4t0 commented on TrpgBot/readme.md
> +
メッセージ例の前に以下みたいなメッセージの解説がほしいかなー

@botへのメンション ①D②+③[]④+⑤
①ダイス数
②ダイスの最大値
③ダイスボーナス
④成功値
⑤成功ボーナス
※[]は半角スペース

2022-05-27 12:49 UTC, t0rn4t0 commented on TrpgBot/dice_goddess.py
> +#ToDo:名前候補ください
名前はこれでいいと思うよ！

2022-05-27 12:49 UTC, t0rn4t0 commented on TrpgBot/dice_goddess.py
> +    pattern = r'([0-9]+)[dD]([0-9]+)[\+\-]?([0-9]+)?\s?([0-9]+)?[\+\-]?([0-9]+)?'
先頭のrってなにこれ...？

2022-05-27 14:55 UTC, ny25mk commented on TrpgBot/trpg_bot.py
> +client = discord.Client(intents=intents)
ごめん、どの部分か分かんない

2022-05-27 15:01 UTC, ny25mk commented on TrpgBot/dice_goddess.py
> +    pattern = r'([0-9]+)[dD]([0-9]+)[\+\-]?([0-9]+)?\s?([0-9]+)?[\+\-]?([0-9]+)?'
エスケープ文字（バックスラッシュ）をそのまま文字列として読むーみたいなやつ
とりあえず入れとけタイプ

参考
https://blog.pyq.jp/entry/python_kaiketsu_190613

2022-05-27 15:17 UTC, ny25mk commented
レビュー対応

2022-05-28 03:01 UTC, t0rn4t0 commented on TrpgBot/trpg_bot.py
> +client = discord.Client(intents=intents)
間違えた(instances)はだめなのかーって話でした

2022-06-04 01:17 UTC, t0rn4t0 requested changes
めちゃめちゃレビュー遅くなって申し訳ない。
mdファイル削除で完成です。

2022-06-09 11:38 UTC, ny25mk commented
ラストリクエストー

2022-06-10 04:27 UTC, ny25mk commented
Botの実行をメンションから変更

ラストリクエストーー

2022-06-11 00:21 UTC, t0rn4t0 reviewed
お疲れさまでした(*- -)(*_ _)ペコリ

2022-06-11 00:21 UTC, merged